### ISSUE TITLE
Caali update broke the module

### ISSUE THREAD

**Issue by Owyn** [teralove/party-death-markers#11]
```
[20:01:37 GMT+0300] ERROR tera-proxy-game: [dispatch] handle: failed to parse S_PARTY_MEMBER_LIST<6>
hook: (anonymous) in party-death-markers-master
...
error: version 6 of message (name: "S_PARTY_MEMBER_LIST", code: 51174) is outdated and cannot be used anymore
```

**Comment by teralove** [comment]
I only have NA installed and Caali proxy dropped support for NA so I'm unable to test it. Looks like S_PARTY_MEMBER_LIST needs to use version 7 now. If anyone can confirm that fixes it and there's no other issues then I'll push an update.

**Comment by Owyn** [comment]
Yea, that's what it is, had to disable autoupdate to apply this fix on my side
