### ISSUE TITLE
not working with lootbeam changes

### ISSUE THREAD

**Issue by 542673** [teralove/party-death-markers#14]
seems to not work anymore as of patch 80

**Comment by teralove** [comment]
looking into it

**Comment by Levi-san** [comment]
Just change the 6 to a 7 on line 44 in index.js.
Old:
  mod.toClient('S_SPAWN_DROPITEM', 6, {

New:
  mod.toClient('S_SPAWN_DROPITEM', 7, {

**Comment by 542673** [comment]
I did modify the line, but still, lootbeams do not spawn

**Comment by Levi-san** [comment]
Did you disable auto-update...?

**Comment by teralove** [comment]
fixed
