### ISSUE TITLE
all markers dissapear on boss reappearing

### ISSUE THREAD

**Issue by Owyn** [teralove/party-death-markers#5]
when boss respawns (deaggros and appears again) - all markers of other still dead party\raid members disappear

**Comment by teralove** [comment]
i'll investigate

**Comment by teralove** [comment]
putting notes here

I encountered this issue once. It was during RKHM last boss and the party wiped. There was a dead body near the player spawn point and someone started the boss a second time. This is when the marker disappeared. A party member or two were also outside the dungeon at the time.

**Comment by Owyn** [comment]
well, his happens pretty much every wipe on Vergos P4, where ppl just die near corners of the map and the healers res them

**Comment by teralove** [comment]
I've been able to consistently reproduce this issue. 

1. Be a party with 2+ members (3 in total)
2. One member dies
3. Another member exits dungeon and re-enters. 

The beacons disappear on dead players when other player rejoin instance. Working on fix.

**Comment by teralove** [comment]
Fixed i think. Was working on the few tests I tried.

**Comment by teralove** [comment]
Going to close this issue if that's ok with you. I haven't encountered this issue since the module was last updated. Guessing that fixed it.
