### ISSUE TITLE
when someone dead leaves party - marker stays

### ISSUE THREAD

**Issue by Owyn** [teralove/party-death-markers#9]
when someone dead leaves party - marker stays

**Comment by FichteFoll** [comment]
This is because of a wrong parameter to `removeMarker` where it should be `member.playerId` instead. As a side effect, #12 fixes this.

https://github.com/teralove/party-death-markers/blob/c1410bc2c3b06cf63a665986dafa23a67e2f7ba7/index.js#L76

**Comment by Raarity** [comment]
This can be close
